trigger: none

pool:
  name: AzDevProdRMAgents

variables:
  NugetSecurityAnalysisWarningLevel: none

steps:

- checkout: self
  clean: true

- powershell: |
    Write-Host "Preloading Azure modules." # This is for better performance, to avoid module-autoloading.
    Import-Module AzureRM, AzureRM.profile, AzureRM.Storage, Azure.Storage, AzureRM.Cdn -ErrorAction Ignore -PassThru
    # work around expectations of Enable-AzureRmAlias
    if (!(Test-Path "$HOME\Documents\WindowsPowerShell\profile.ps1"))
    {
      New-Item -Path "$HOME\Documents\WindowsPowerShell\profile.ps1" -ItemType File -Force
    }
    Enable-AzureRmAlias -Scope CurrentUser
    $uploadFiles = New-Object System.Collections.ArrayList
    $certificateThumbprint = (Get-ItemProperty -Path "$(ServicePrincipalReg)").ServicePrincipalCertThumbprint
    $clientId = (Get-ItemProperty -Path "$(ServicePrincipalReg)").ServicePrincipalClientId
    Write-Host "##vso[task.setsecret]$certificateThumbprint"
    Write-Host "##vso[task.setsecret]$clientId"
    Write-Host "logging in"
    $ten = "$(TenantId)".Insert(10,' ')
    Write-Host "tenant $ten"
    Login-AzureRmAccount -ServicePrincipal -CertificateThumbprint $certificateThumbprint -ApplicationId $clientId -TenantId $(TenantId)
    $sub = "$(SubscriptionId)".Insert(10,' ')
    Write-Host "selecting subscription $sub"
    Select-AzureRmSubscription -SubscriptionId $(SubscriptionId)
    Write-Host "getting storage account"
    $storage = Get-AzureRmStorageAccount -ResourceGroupName vstsagentpackage -AccountName vstsagentpackage
