parameters:
- name: version
  type: string
  displayName: Version
- name: derivedFrom
  type: string
  displayName: Derived From Version
  default: latest
- name: skipTests
  type: boolean
  default: false
  displayName: Skip Tests

variables:
  releaseBranch: releases/${{ parameters.version }}

extends:
  template: .azure-pipelines/pipeline.yml
  parameters:
    branch:  ${{ variables.releaseBranch }}
    componentDetection: false
    test: ${{ not(parameters.skipTests) }}
    sign: true
    publishArtifacts: true

    preBuildStages:
    - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      - stage: Create_Release_Branch
        displayName: Create Release Branch
        jobs:
        ################################################################################
        - job: Create_Release_Branch
        ################################################################################
          displayName: Create Release Branch
          pool:
            vmImage: ubuntu-18.04

          steps:
          - checkout: self

          - script: |
              cd release
              npm install
              node createReleaseBranch.js ${{ parameters.version }} --derivedFrom=${{ parameters.derivedFrom }}
            env:
              EDITOR: cat
              PAT: $(GithubToken)
            displayName: Push release branch to GitHub

    postBuildStages:
    - stage: CreatePRs
      jobs:
      ################################################################################
      - job: create_ado_prs
      ################################################################################
        displayName: Create PRs in AzureDevOps
        pool:
          vmImage: ubuntu-18.04

        steps:
        - checkout: self

        - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
          - script: git checkout ${{ variables.releaseBranch }}
            displayName: Checkout release branch

        - bash: |
            set -x
            cd release
            npm install
            ls
            node createAdoPrs.js ${{ parameters.version }}
          displayName: Create PRs in AzureDevOps and AzureDevOps.ConfigChange
          env:
            USER: $(User)
            PAT: $(AdoPAT)
