parameters:
- name: version
  type: string
  displayName: Version
- name: derivedFrom
  type: string
  displayName: Derived From Version
  default: latest
- name: skipTests
  type: boolean
  default: false
  displayName: Skip Tests
# buildStageOnly is useful for testing changes of the build stage which cannot be tested
# in the ci project, like signing, without actually doing a release
- name: buildStageOnly
  type: boolean
  default: false
  displayName: Build Stage Only

variables:
  releaseBranch: releases/${{ parameters.version }}

extends:
  template: .azure-pipelines/pipeline.yml
  parameters:
    branch:  ${{ variables.releaseBranch }}
    componentDetection: false
    test: ${{ not(parameters.skipTests) }}
    sign: true
    publishArtifacts: true

    ${{ if not(parameters.buildStageOnly) }}:
      preBuildStages:
      - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
        - stage: Create_Release_Branch
          displayName: Create Release Branch
          jobs:
          ################################################################################
          - job: Create_Release_Branch
          ################################################################################
            displayName: Create Release Branch
            pool:
              vmImage: ubuntu-18.04

            steps:
            - checkout: self

    ${{ if not(parameters.buildStageOnly) }}:
      postBuildStages:
      - stage: Release
        jobs:
        ################################################################################
        - job: publish_agent_packages
        ################################################################################
          displayName: Publish Agents (Windows/Linux/OSX)
          pool:
            name: AzDevProdRMAgents
          steps:

          # Clean
          - checkout: self
            clean: true

          # Upload agent packages to Azure blob storage and refresh Azure CDN
          - powershell: |
              Enable-AzureRmAlias -Scope CurrentUser
